### ISSUE TITLE
我的钱包卡在88.1%好久了，差不多有一天了，不知道该怎么办

### ISSUE THREAD

**Issue by popoleaf** [bitcoin69fullpow/bitcoin69#1]
我的钱包卡在88.1%好久了，差不多有一天了，不知道该怎么办

**Comment by bitcoin69fullpow** [comment]
![image](https://github.com/bitcoin69fullpow/bitcoin69/assets/157883898/8cea523a-b46a-445f-b3db-3a261d6eee93)

**Comment by bitcoin69fullpow** [comment]
![awsd](https://github.com/bitcoin69fullpow/bitcoin69/assets/157883898/aa2e29fb-10ee-4f13-a3ba-c904e0d50f1d)

**Comment by popoleaf** [comment]
我换了部电脑重新弄，好了，谢谢。
